name: Build Fuel Prometheus Exporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish-docker-image:
    uses: FuelLabs/github-actions/.github/workflows/docker-build-push.yml@master
    secrets:
      REGISTRY_USERNAME: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      auth-mode: registry-login
      registry: ghcr.io
      build-backend: native
      platforms: linux/amd64,linux/arm64
      runs-on-amd64: ubuntu-latest
      runs-on-arm64: ubuntu-24.04-arm
      dockerfile: Dockerfile
      docker-context: .
      image: ghcr.io/fuellabs/prometheus-fuel-exporter
      flavor: latest=${{ github.ref == 'refs/heads/main' }}
      tags: |
        type=sha
        type=ref,event=branch
        type=ref,event=tag
        type=semver,pattern={{raw}}
        type=raw,value=sha-{{sha}}-{{date 'YYYYMMDDhhmmss'}}
